schedules:
  type: objects
  default: []
  schema:
    name: schedule
    identifier: name
    properties:
      name:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 100
      start_month:
        type: enum
        required: true
        default: January
        choices:
          - January
          - February
          - March
          - April
          - May
          - June
          - July
          - August
          - September
          - October
          - November
          - December
      start_day:
        type: integer
        required: true
        default: 1
        validations:
          min: 1
          max: 31
      end_month:
        type: enum
        required: true
        default: December
        choices:
          - January
          - February
          - March
          - April
          - May
          - June
          - July
          - August
          - September
          - October
          - November
          - December
      end_day:
        type: integer
        required: true
        default: 31
        validations:
          min: 1
          max: 31
      logo:
        type: upload
      logo_dark:
        type: upload
      logo_small:
        type: upload
      logo_small_dark:
        type: upload
      mobile_logo:
        type: upload
      mobile_logo_dark:
        type: upload
